services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: anas.abdelaziz
      POSTGRES_PASSWORD: anas.abdelaziz
      POSTGRES_DB: nexus_db
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: anas.abdelaziz
      MONGO_INITDB_ROOT_PASSWORD: anas.abdelaziz
    ports:
      - "27017:27017"
    volumes:
    - mongo_data:/data/db
  
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: anas.abdelaziz
      RABBITMQ_DEFAULT_PASS: anas.abdelaziz
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"      #Messaging
      - "15672:15672"    #UI
volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:

